#!/bin/bash
bashname=$0
subfolder=$1
name=$2
echo "Вы запустили script с именем $bashname и параметрами: $subfolder, $name"
cd "$subfolder"
for file in *
do
if [[ "$file" =~ ^[0-9]{1}\.[[:alnum:]]{2,5} ]]; then
echo "Refreshing file $file"
mv "$file" "000$file"
if [ -f file ]; then
echo "Deleting file $file"
rm "$file"
fi
fi
if [[ "$file" =~ ^[0-9]{2}\.[[:alnum:]]{2,5} ]]; then
mv "$file" "00$file"
echo "Refreshing file $file"
if [ -f file ]; then
echo "Deleting file $file"
rm "$file"
fi
fi
if [[ "$file" =~ ^[0-9]{3}\.[[:alnum:]]{2,5} ]]; then
mv "$file" "0$file"
echo "Refreshing file $file"
if [ -f file ]; then
echo "Deleting file $file"
rm "$file"
fi
fi
done
echo "Refreshing all files..."
for file in *
do
touch "$file"
done
echo "$bashname is done"
exit 0